services:
  mongo:
    image: mongo:8-noble
    restart: always
    env_file:
      - .env.develop
#     the env file auto-injects the env vars needed by mongo
    ports:
      - "${MONGO_HOST_PORT:-27017}:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
